"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Header} from './Components/header';
import {Footer} from './Components/footer';
import { Provider } from "react-redux";
import { store } from "./store";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
    <html lang="en">
    <head>


<script src='https://kit.fontawesome.com/a076d05399.js'></script>

</head>
     
      <body className="bg-gradient-to-b from-blue-500" > <Header/> {children}
      <Footer/>
      </body>
    </html>
    </Provider>
  )
}
